"""
STEP 2 (Final) — DistilBERT Text Emotion Model Training
AI Mental Health Companion | Capstone Project
===========================================================
MLOps Techniques Applied:
1. Class Weights    — rare emotions get more attention
2. Focal Loss       — focuses training on hard examples
3. Per-emotion thresholds — optimized per emotion at inference

📁 File location: mental_health_companion/text_model/train_text_model.py
📋 Requires: train.csv, val.csv (generated by preprocess.py + augment_data.py)
"""

import os
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
from transformers import DistilBertTokenizerFast, DistilBertForSequenceClassification
from torch.optim import AdamW
from transformers import get_scheduler
from sklearn.metrics import f1_score, classification_report
from tqdm import tqdm
import json

# ── CONFIGURATION ─────────────────────────────────────────────────────────────
CONFIG = {
    "model_name"    : "distilbert-base-uncased",
    "max_length"    : 128,
    "batch_size"    : 16,
    "epochs"        : 8,
    "learning_rate" : 2e-5,
    "output_dir"    : "saved_model",
}

# ── 11 EMOTION COLUMNS ────────────────────────────────────────────────────────
EMOTION_COLS = [
    'joy',                                          # positive
    'sadness', 'nervousness', 'fear', 'anger',      # negative
    'disappointment', 'remorse', 'embarrassment',   # negative
    'disgust', 'neutral'                            # negative + neutral
]

NUM_LABELS = len(EMOTION_COLS)
print(f"Training with {NUM_LABELS} emotions: {EMOTION_COLS}")

# ── CHECK DEVICE ──────────────────────────────────────────────────────────────
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")


# ── FOCAL LOSS ────────────────────────────────────────────────────────────────
class FocalLoss(nn.Module):
    """
    Focal Loss for multi-label classification.

    Why Focal Loss?
    - Standard loss treats all examples equally
    - Focal Loss focuses MORE on hard/misclassified examples
    - Automatically down-weights easy examples (common emotions)
    - Up-weights hard examples (rare emotions)

    gamma: focusing parameter
    - gamma=0 → standard BCE loss
    - gamma=2 → standard focal loss (best for imbalanced data)

    alpha: class weights tensor
    - Higher weight → model pays more attention to that emotion
    """
    def __init__(self, alpha=None, gamma=2.0):
        super(FocalLoss, self).__init__()
        self.alpha = alpha  # class weights
        self.gamma = gamma  # focusing parameter

    def forward(self, logits, targets):
        # Standard BCE loss
        bce_loss = nn.functional.binary_cross_entropy_with_logits(
            logits, targets, reduction='none'
        )

        # Apply focal weight
        probs        = torch.sigmoid(logits)
        p_t          = probs * targets + (1 - probs) * (1 - targets)
        focal_weight = (1 - p_t) ** self.gamma
        focal_loss   = focal_weight * bce_loss

        # Apply class weights if provided
        if self.alpha is not None:
            focal_loss = focal_loss * self.alpha

        return focal_loss.mean()


# ── CLASS WEIGHTS ─────────────────────────────────────────────────────────────
def compute_class_weights(train_df):
    """
    Computes class weights based on emotion frequency.

    Formula: weight = total_samples / (num_classes * class_count)
    - Common emotions (joy, neutral) → low weight
    - Rare emotions (embarrassment, remorse) → high weight

    This tells the model: pay MORE attention to rare emotions.
    """
    weights = []
    total   = len(train_df)

    for emotion in EMOTION_COLS:
        count  = train_df[emotion].sum()
        weight = total / (NUM_LABELS * max(count, 1))
        weights.append(weight)

    # Normalize weights to range [0.5, 3.0]
    weights    = np.array(weights)
    normalized = 0.5 + (weights - weights.min()) / (weights.max() - weights.min()) * 2.5

    print("\nClass weights per emotion:")
    for emotion, w in zip(EMOTION_COLS, normalized):
        print(f"  {emotion:<15} {w:.3f}")

    return torch.tensor(normalized, dtype=torch.float).to(device)


# ── PER-EMOTION THRESHOLDS ────────────────────────────────────────────────────
def compute_thresholds(train_df):
    """
    Computes per-emotion detection thresholds based on sample count.

    Logic:
    - Common emotions → higher threshold (0.5) — we're strict
    - Rare emotions   → lower threshold (0.25) — we're lenient

    This ensures rare emotions are not missed during inference.
    """
    thresholds = {}
    total      = len(train_df)

    for emotion in EMOTION_COLS:
        count = train_df[emotion].sum()
        ratio = count / total

        # Map ratio to threshold range [0.25, 0.5]
        if ratio >= 0.3:
            thresholds[emotion] = 0.50   # very common
        elif ratio >= 0.1:
            thresholds[emotion] = 0.45   # common
        elif ratio >= 0.05:
            thresholds[emotion] = 0.40   # medium
        elif ratio >= 0.02:
            thresholds[emotion] = 0.35   # rare
        else:
            thresholds[emotion] = 0.25   # very rare

    print("\nPer-emotion thresholds:")
    for emotion, t in thresholds.items():
        print(f"  {emotion:<15} {t:.2f}")

    return thresholds


# ── DATASET CLASS ─────────────────────────────────────────────────────────────
class EmotionDataset(Dataset):
    """
    Custom PyTorch Dataset.
    Tokenizes text and returns input tensors + emotion labels.
    """
    def __init__(self, dataframe, tokenizer, max_length):
        self.texts      = dataframe['text'].tolist()
        self.labels     = dataframe[EMOTION_COLS].values.astype(np.float32)
        self.tokenizer  = tokenizer
        self.max_length = max_length

    def __len__(self):
        return len(self.texts)

    def __getitem__(self, idx):
        encoding = self.tokenizer(
            self.texts[idx],
            max_length=self.max_length,
            padding='max_length',
            truncation=True,
            return_tensors='pt'
        )
        return {
            'input_ids'     : encoding['input_ids'].squeeze(0),
            'attention_mask': encoding['attention_mask'].squeeze(0),
            'labels'        : torch.tensor(self.labels[idx], dtype=torch.float)
        }


# ── LOAD DATA ─────────────────────────────────────────────────────────────────
print("\nLoading data...")
train_df = pd.read_csv('train.csv')
val_df   = pd.read_csv('val.csv')
print(f"  Train: {len(train_df):,} samples")
print(f"  Val  : {len(val_df):,} samples")

# ── COMPUTE CLASS WEIGHTS AND THRESHOLDS ──────────────────────────────────────
class_weights = compute_class_weights(train_df)
thresholds    = compute_thresholds(train_df)

# ── INITIALIZE FOCAL LOSS ─────────────────────────────────────────────────────
criterion = FocalLoss(alpha=class_weights, gamma=2.0)

# ── LOAD TOKENIZER AND MODEL ──────────────────────────────────────────────────
print("\nLoading DistilBERT tokenizer and model...")
tokenizer = DistilBertTokenizerFast.from_pretrained(CONFIG["model_name"])
model     = DistilBertForSequenceClassification.from_pretrained(
    CONFIG["model_name"],
    num_labels=NUM_LABELS,
    problem_type="multi_label_classification"
)
model = model.to(device)
print("  Model loaded successfully!")

# ── DATALOADERS ───────────────────────────────────────────────────────────────
train_dataset = EmotionDataset(train_df, tokenizer, CONFIG["max_length"])
val_dataset   = EmotionDataset(val_df,   tokenizer, CONFIG["max_length"])

train_loader = DataLoader(
    train_dataset, batch_size=CONFIG["batch_size"], shuffle=True
)
val_loader = DataLoader(
    val_dataset, batch_size=CONFIG["batch_size"], shuffle=False
)

# ── OPTIMIZER AND SCHEDULER ───────────────────────────────────────────────────
optimizer          = AdamW(model.parameters(), lr=CONFIG["learning_rate"])
num_training_steps = CONFIG["epochs"] * len(train_loader)
scheduler          = get_scheduler(
    "linear",
    optimizer=optimizer,
    num_warmup_steps=int(0.1 * num_training_steps),
    num_training_steps=num_training_steps
)


# ── TRAINING FUNCTION ─────────────────────────────────────────────────────────
def train_one_epoch(model, loader, optimizer, scheduler, criterion, device):
    """
    Runs one full pass through training data using Focal Loss.
    """
    model.train()
    total_loss = 0

    for batch in tqdm(loader, desc="Training"):
        input_ids      = batch['input_ids'].to(device)
        attention_mask = batch['attention_mask'].to(device)
        labels         = batch['labels'].to(device)

        # Forward pass
        outputs = model(input_ids=input_ids, attention_mask=attention_mask)

        # Compute focal loss
        loss = criterion(outputs.logits, labels)

        # Backward pass
        optimizer.zero_grad()
        loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
        optimizer.step()
        scheduler.step()

        total_loss += loss.item()

    return total_loss / len(loader)


# ── EVALUATION FUNCTION ───────────────────────────────────────────────────────
def evaluate(model, loader, thresholds, device):
    """
    Evaluates model using per-emotion thresholds.
    Each emotion has its own optimized detection threshold.
    """
    model.eval()
    total_loss = 0
    all_preds  = []
    all_labels = []

    # Convert thresholds dict to tensor
    threshold_tensor = torch.tensor(
        [thresholds[e] for e in EMOTION_COLS],
        dtype=torch.float
    ).to(device)

    with torch.no_grad():
        for batch in tqdm(loader, desc="Evaluating"):
            input_ids      = batch['input_ids'].to(device)
            attention_mask = batch['attention_mask'].to(device)
            labels         = batch['labels'].to(device)

            outputs    = model(
                input_ids=input_ids,
                attention_mask=attention_mask,
                labels=labels
            )
            total_loss += outputs.loss.item()

            # Apply per-emotion thresholds
            probs = torch.sigmoid(outputs.logits)
            preds = (probs > threshold_tensor).int().cpu().numpy()

            all_preds.append(preds)
            all_labels.append(labels.int().cpu().numpy())

    all_preds  = np.vstack(all_preds)
    all_labels = np.vstack(all_labels)

    f1 = f1_score(all_labels, all_preds, average='macro', zero_division=0)
    return total_loss / len(loader), f1, all_preds, all_labels


# ── TRAINING LOOP ─────────────────────────────────────────────────────────────
print(f"\nStarting training for {CONFIG['epochs']} epochs...")
print("⏳ Running on GPU — should take ~30-40 minutes\n")

best_f1 = 0
history = []

for epoch in range(CONFIG["epochs"]):
    print(f"\n{'='*50}")
    print(f"Epoch {epoch+1} / {CONFIG['epochs']}")
    print(f"{'='*50}")

    train_loss = train_one_epoch(
        model, train_loader, optimizer,
        scheduler, criterion, device
    )
    val_loss, val_f1, preds, labels = evaluate(
        model, val_loader, thresholds, device
    )

    print(f"\n  Train Loss : {train_loss:.4f}")
    print(f"  Val Loss   : {val_loss:.4f}")
    print(f"  Val F1     : {val_f1:.4f}")

    history.append({
        "epoch"     : epoch + 1,
        "train_loss": round(train_loss, 4),
        "val_loss"  : round(val_loss,   4),
        "val_f1"    : round(val_f1,     4)
    })

    if val_f1 > best_f1:
        best_f1 = val_f1
        os.makedirs(CONFIG["output_dir"], exist_ok=True)

        # Save emotion labels and thresholds into model config
        model.config.id2label    = {i: e for i, e in enumerate(EMOTION_COLS)}
        model.config.label2id    = {e: i for i, e in enumerate(EMOTION_COLS)}
        model.config.thresholds  = thresholds

        model.save_pretrained(CONFIG["output_dir"])
        tokenizer.save_pretrained(CONFIG["output_dir"])
        print(f"  ✅ Best model saved! (F1: {best_f1:.4f})")


# ── FINAL REPORT ──────────────────────────────────────────────────────────────
print(f"\n{'='*50}")
print("TRAINING COMPLETE")
print(f"Best Validation F1: {best_f1:.4f}")
print(f"{'='*50}")

_, _, final_preds, final_labels = evaluate(
    model, val_loader, thresholds, device
)
report = classification_report(
    final_labels, final_preds,
    target_names=EMOTION_COLS,
    zero_division=0
)
print("\nPer-Emotion Classification Report:")
print(report)

# ── SAVE HISTORY AND CONFIG ───────────────────────────────────────────────────
with open("training_history.json", "w") as f:
    json.dump(history, f, indent=2)

with open(os.path.join(CONFIG["output_dir"], "training_config.json"), "w") as f:
    json.dump({
        **CONFIG,
        "emotions"  : EMOTION_COLS,
        "thresholds": thresholds
    }, f, indent=2)

print("\n✅ Training history saved to training_history.json")
print(f"✅ Model saved to '{CONFIG['output_dir']}/' folder")